from selenium.webdriver.common.by import By

class Locators_user:

    login_phone_field = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]")
    send_me_code_btn = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]")
    login_password_field = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/span[1]/form[1]/div[1]/div[1]/span[1]/div[1]/input[1]")
    login_btn = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/span[1]/form[1]/input[1]")
    users = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/div[1]/nav[1]/div[2]/a[23]")
    users_text = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[1]/span[1]/h4[1]")
    users_btn = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[1]/span[1]/span[1]/i[1]")
    search = (By.XPATH,"//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/span[1]/span[1]/div[1]/input[1]")
    english_icon = (By.XPATH, "//body[1]/div[1]/div[1]/div[1]")
    hebrew_icon = (By.XPATH, "//body[1]/div[1]/div[1]/div[1]")
    display_text = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[3]")
    numbers_display_button = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[1]/input[1]")
    display_50 = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[2]/div[1]/div[2]")
    display_20 = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[1]/div[1]/div[1]")
    display_75 = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[2]/div[1]/div[3]")
    display_100 = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[2]/div[1]/div[4]")
    display_150 = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[2]/div[1]/div[5]")
    display_200 = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[2]/div[1]/div[6]")
    display_all = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[1]/span[1]/div[2]/div[1]/div[7]")
    single_arrow = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[4]/i[1]")
    double_arrow = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[5]/i[1]")
    number_change_forward = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[2]")
    number_change_backward = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[1]")
    setting = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[1]/span[1]/i[1]")
    add_user_fild = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]")
    add_user = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]")
    active_btn = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[17]/span[1]/span[1]")
    add_user_x_btn = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/span[1]/i[1]")
    add_user_text = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/h4[1]/span[1]")
    store_field = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/span[1]/div[2]/input[1]")
    first_name = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[2]/span[1]/div[1]/input[1]")
    last_name = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[3]/span[1]/div[1]/input[1]")
    email = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/div[1]/input[1]")
    phone = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[5]/span[1]/div[1]/input[1]")
    city = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/div[1]/span[1]/div[1]/input[1]")
    street = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/div[2]/span[1]/div[1]/input[1]")
    building = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[8]/div[1]/div[3]/span[1]/div[1]/input[1]")
    account_owner = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/div[1]/span[1]/div[1]/input[1]")
    account_number = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/div[2]/span[1]/div[1]/input[1]")
    bank_name = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[9]/div[1]/div[4]/span[1]/div[1]/input[1]")
    credit_account_active = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[10]/span[1]/span[1]")
    balance = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[11]/div[1]/div[1]/span[1]/div[1]/input[1]")
    income = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[11]/div[1]/div[2]/span[1]/div[1]/input[1]")
    outcome = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[11]/div[1]/div[3]/span[1]/div[1]/input[1]")
    id = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[12]/span[1]/div[1]/input[1]")
    ETrado_approved = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[14]/span[1]/span[1]")
    business_type = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[17]/span[1]/div[2]/input[1]")
    update_btn = (By.XPATH, "//body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/input[1]")
    add_user_btn = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/input[1]")
    yetsuwa = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]")
    add_by_brand = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/span[2]")
    structure = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[5]")
    yevuwa = (By.XPATH, "//body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[4]")
    user_first_data = (By.XPATH, "//tbody/tr/td[1]")
    menu_scroll = (By.CLASS_NAME, "menu_scroll")
    non_row_txt = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]")
    all_txt = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]")
    add_by_brand_text = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[4]/div[1]/div[1]/form[1]/div[1]/div[1]/label[1]")
    single_number_before_txt = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[1]")
    double_num_before_txt = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[8]")
    second_num_txt = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[2]/div[1]/div[2]/div[2]/div[2]/span[3]")
    user_txt_english = (By.XPATH, "/html[1]/body[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[1]/span[1]/h4[1]")


